[project]
name = "pbwpfvc"
r_version = ">=4.5.0"

[dependencies]
EValue = "*"
GLMMadaptive = "*"
JMbayes2 = "*"
arrow = "*"
broom = "*"
collapse = "*"
"data.table" = "*"
dplyr = "*"
fst = "*"
here = "*"
jsonlite = "*"
lubridate = "*"
metafor = "*"
nlme = "*"
patchwork = "*"
readr = "*"
rspiro = "*"
scales = "*"
stringr = "*"
survival = "*"
tidyverse = "*"
vctrs = "*"

[dependencies.clifR]
git = "AartikSarma/clifR"
rev = "a701d83e5883989383a69872bc8b14df6dade0c7"
